# -*- coding: utf-8 -*-
"""Drive - Projeo RPG dia a dia para crianças e jovens neurotípicos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gl0FwXBIxoVdLR--BK127xBUv1YWGl7h
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

from google import genai
client = genai.Client()
MODEL_ID = "gemini-2.0-flash"

!pip install -q google-adk

!pip install -q Pillow

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.colab import drive
drive.mount('/content/drive')
from google.genai import types
from datetime import date
import textwrap
from google.colab import drive
from PIL import Image
import os
from IPython.display import display, Markdown
import requests
import warnings

warnings.filterwarnings("ignore")
import textwrap
from IPython.display import display, Markdown
import requests
import warnings

warnings.filterwarnings("ignore")

def call_agent(agent: Agent, message_text: str) -> str:
    session_service = InMemorySessionService()
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# ---      Agente 0: Introdução      --- #
##########################################
import os
from IPython.display import display, Image, Markdown
from google.colab import drive

# Se o Drive ainda não estiver montado, descomente a linha abaixo e execute a célula
drive.mount('/content/drive')

def agente_apresentacao():
    """
    Agente 0: Pergunta o gênero, exibe a capa da apresentação do RPG correspondente
    e pergunta se o usuário está pronto. Retorna True se estiver pronto, False caso contrário.
    """
    print("\nAGENTE 0: Iniciando a apresentação da nossa incrível aventura!")

    pasta_apresentacao = '/content/drive/MyDrive/Apresentacao_RPG' # Ajuste o caminho se necessário
    nome_arquivo_capa = 'Capa_RPG'
    extensao_arquivo = '.png'
    genero = ''

    while True:
        escolha_genero = input("\nVocê é um aventureiro (M) ou aventureira (F)? (Digite M ou F)\n").strip().upper()
        if escolha_genero == 'M':
            genero = '_M'
            break
        elif escolha_genero == 'F':
            genero = '_F'
            break
        else:
            print("Opção inválida. Por favor, digite 'M' para masculino ou 'F' para feminino.")

    caminho_arquivo_capa = os.path.join(pasta_apresentacao, f"{nome_arquivo_capa}{genero}{extensao_arquivo}")

    try:
        display(Image(filename=caminho_arquivo_capa))
    except FileNotFoundError:
        print(f"Erro: Arquivo da capa não encontrado em {caminho_arquivo_capa}")
    except Exception as e:
        print(f"Ocorreu um erro ao exibir a imagem da capa: {e}")


# Para usar o Agente 0:
if agente_apresentacao():
    # Aqui você chamaria o Agente 1
    print("\n--- Iniciando o Agente 1 ---")
    # Coloque a chamada para a função do Agente 1 aqui (ex: ficha_do_heroi = agente_setup())
else:
    print("\nA apresentação foi interrompida.")

##########################################
# --- Agente 1: Agente de Setup --- #
##########################################
import os
from IPython.display import Image as DisplayImage
import matplotlib.pyplot as plt
from PIL import Image
from google.colab import drive

# Se o Drive ainda não estiver montado, descomente a linha abaixo e execute a célula
drive.mount('/content/drive')

def agente_setup():
    """
    Agente 1: Coleta informações do jogador, apresenta os personagens com opções numéricas,
    permite a escolha por número e exibe a ficha do personagem.
    """
    nome_jogador = input("Olá aventureiro(a)! Qual o seu nome? ")

    personagens_disponiveis = {
        1: {
            "Nome": "Bruxa das Chamas Sábias",
            "Classe": "Bruxa",
            "Título": "Guardiã da Chama do Conhecimento",
            "Atributos": {"Inteligência": 9, "Sabedoria": 8, "Destreza": 4, "Reflexo": 3},
            "Habilidades Especiais": [
                "Leitura Arcana: Pode recomeçar o tempo de uma missão (1x por dia com teste de sabedoria dificuldade alta).",
                "Mente Analítica: +2 nos testes de leitura, interpretação de texto, raciocínio lógico ou matemática. (ganha mais 15 minutos, dificuldade média)"
            ],
            "Descrição": "A Bruxa das Chamas Sábias domina os mistérios do saber. Sempre com um livro em mãos e olhos atentos, ela resolve problemas como quem lança feitiços: com paciência, estratégia e foco. Não gosta de pressa nem bagunça. Mas com tempo e concentração, é capaz de vencer qualquer desafio mental.",
            "nome_arquivo_ficha": "bruxa_chamas_sabias.png"
        },
        2: {
            "Nome": "Feiticeira dos Raios Rápidos",
            "Classe": "Feiticeira",
            "Título": "Guardiã da Tempestade Interior",
            "Atributos": {"Inteligência": 5, "Sabedoria": 4, "Destreza": 7, "Reflexo": 10},
            "Habilidades Especiais": [
                "Ação Relâmpago: Uma vez por dia, pode trocar uma tarefa chata por uma versão mais curta (com metade do XP, dificuldade alta).",
                "Bônus de Velocidade: +3 nos testes com tempo limitado (como concluir tarefas antes do tempo acabar, dificuldade média).",
                "Foco Instantâneo: Quando está totalmente focada, pode jogar 2 dados e escolher o melhor resultado (1x por dia)."
            ],
            "Descrição": "A Feiticeira dos Raios Rápidos é pura energia em forma de magia. Seus pensamentos são velozes como o trovão, e seus movimentos quase não podem ser vistos. Perfeita para missões em que o tempo é curto e a concentração precisa ser certeira. Mas cuidado — o mesmo raio que ilumina, também pode dispersar!",
            "nome_arquivo_ficha": "feiticeira_raios_rapidos.png"
        },
        3: {
            "Nome": "Druida do Vento Brincalhão",
            "Classe": "Druida",
            "Título": "Guardiã da Alegria e Movimento",
            "Atributos": {"Inteligência": 6, "Sabedoria": 6, "Destreza": 9, "Reflexo": 8},
            "Habilidades Especiais": [
                "Espírito Livre: Pode trocar a ordem de duas tarefas do dia sem perder XP.",
                "Bônus Natural: +2 em tarefas que envolvam desenho, organização do ambiente ou criatividade.",
                "Foco Ventoso: Quando está ouvindo música ou se movendo, ganha +2 em testes de tempo e agilidade."
            ],
            "Descrição": "A Druida do Vento Brincalhão é leve como uma pluma e curiosa como um esquilo. Adora cores, movimento e coisas novas. Não suporta mesmice nem obrigações sem sentido. Mas com liberdade e diversão, transforma qualquer tarefa em mágica — mesmo as mais difíceis!",
            "nome_arquivo_ficha": "druida_vento_brincalhao.png"
        }
    }

    print("\nConheça os heróis que podem te ajudar nessa aventura:")
    for numero, info in personagens_disponiveis.items():
        print(f"{numero} - {info['Nome']} ({info['Classe']}, {info['Título']}):")
        print(f"  ✨ Atributos: {info['Atributos']}")
        print(f"  📜 Habilidades Especiais: {', '.join(info['Habilidades Especiais'])}")
        print(f"  📚 Descrição: {info['Descrição'][:100]}...") # Mostra só um trecho da descrição
        print("-" * 30)

    while True:
        escolha = input("Escolha seu herói digitando o número correspondente (1, 2 ou 3):\n").strip()
        if escolha in ["1", "2", "3"]:
            numero_escolhido = int(escolha)
            personagem_escolhido = personagens_disponiveis[numero_escolhido]
            ficha_personagem = {
                "Nome do Jogador": nome_jogador,
                "Nome do Personagem": personagem_escolhido["Nome"],
                "Classe": personagem_escolhido["Classe"],
                "Título": personagem_escolhido["Título"],
                "Atributos": personagem_escolhido["Atributos"],
                "Habilidades Especiais": personagem_escolhido["Habilidades Especiais"],
                "Descrição": personagem_escolhido["Descrição"],
                "nome_arquivo_ficha": personagem_escolhido["nome_arquivo_ficha"]
            }
            print("\nFicha do seu personagem:")
            for chave, valor in ficha_personagem.items():
                if chave == "Atributos":
                    print(f"  - {chave}:")
                    for atributo, valor_atributo in valor.items():
                        print(f"    - {atributo}: {valor_atributo}")
                elif chave == "Habilidades Especiais":
                    print(f"  - {chave}:")
                    for habilidade in valor:
                        print(f"    - {habilidade}")
                else:
                    print(f"  - {chave}: {valor}")

            pasta_fichas = '/content/drive/MyDrive/FichaPersonagens'
            caminho_ficha_imagem = os.path.join(pasta_fichas, ficha_personagem["nome_arquivo_ficha"])

            try:
                img = Image.open(caminho_ficha_imagem)
                print(f"\n Legal {nome_jogador}, boa escolha, aqui está a sua ficha...")
                plt.imshow(img)
                plt.axis('off')
                plt.show()
            except FileNotFoundError:
                print(f"Erro: Arquivo da ficha não encontrado em {caminho_ficha_imagem}")
            except Exception as e:
                print(f"Ocorreu um erro ao abrir a imagem da ficha: {e}")

            return ficha_personagem
        else:
            print("Opção inválida. Por favor, digite 1, 2 ou 3 para escolher seu herói.")

# Para testar o Agente 1:
ficha = agente_setup()
# print("Ficha final criada (para o próximo agente):", ficha)

################################################
# ---          Agente 2: Missões           --- #
################################################
from PIL import Image, ImageDraw, ImageFont
import os
import matplotlib.pyplot as plt

def agente_missoes(ficha_personagem):
    """
    Agente 2: Pergunta aos responsáveis sobre as dificuldades da criança
    e ajusta os valores de dificuldade das missões.
    """
    print("\nPreparem-se, aventureiros e responsáveis! O Mago Supremo da Aventura precisa da ajuda de vocês para preparar os desafios à altura do nosso herói!")

    # Pergunta sobre a área de maior dificuldade (Casa ou Escola)
    while True:
        area_dificuldade = input("\nEm qual área a criança precisa de mais atenção?\n1 - Casa\n2 - Escola\nDigite o número da sua escolha:\n").strip()
        if area_dificuldade in ["1", "2"]:
            area_dificuldade = int(area_dificuldade)
            break
        else:
            print("Opção inválida. Por favor, digite 1 para Casa ou 2 para Escola.")

    # Dificuldades das tarefas de casa
    dificuldades_casa = {}
    print("\nAgora, vamos definir a dificuldade das Tarefas de Casa (mais difícil primeiro):")
    tarefas_casa = ["Higiene", "Lavar a Louça", "Arrumar Quarto"]
    niveis_dificuldade = {"1": "Difícil", "2": "Média", "3": "Fácil"}
    valores_dificuldade = {"Difícil": 24, "Média": 20, "Fácil": 18}

    for i in range(3):
        while True:
            escolha = input(f"Qual a dificuldade da tarefa '{tarefas_casa[i]}' (1-Difícil, 2-Média, 3-Fácil)?\n").strip()
            if escolha in ["1", "2", "3"] and niveis_dificuldade[escolha] not in dificuldades_casa.values():
                dificuldade_escolhida = niveis_dificuldade[escolha]
                valor_dificuldade = valores_dificuldade[dificuldade_escolhida]
                if area_dificuldade == 1: # Se Casa foi escolhido como mais difícil
                    valor_dificuldade += 2
                dificuldades_casa[tarefas_casa[i]] = valor_dificuldade
                break
            elif escolha not in ["1", "2", "3"]:
                print("Opção inválida. Por favor, digite 1, 2 ou 3.")
            else:
                print("Essa dificuldade já foi escolhida. Por favor, escolha outra.")

    # Dificuldades das matérias escolares
    dificuldades_escola = {}
    print("\nAgora, vamos definir a dificuldade das Matérias Escolares (mais difícil primeiro):")
    materias_escola = ["Matemática / Ciências", "Português / Literatura", "História / Geografia"]

    for i in range(3):
        while True:
            escolha = input(f"Qual a dificuldade de '{materias_escola[i]}' (1-Difícil, 2-Média, 3-Fácil)?\n").strip()
            if escolha in ["1", "2", "3"] and niveis_dificuldade[escolha] not in dificuldades_escola.values():
                dificuldade_escolhida = niveis_dificuldade[escolha]
                valor_dificuldade = valores_dificuldade[dificuldade_escolhida]
                if area_dificuldade == 2: # Se Escola foi escolhido como mais difícil
                    valor_dificuldade += 2
                dificuldades_escola[materias_escola[i]] = valor_dificuldade
                break
            elif escolha not in ["1", "2", "3"]:
                print("Opção inválida. Por favor, digite 1, 2 ou 3.")
            else:
                print("Essa dificuldade já foi escolhida. Por favor, escolha outra.")

    missoes = {
        "escola": [
            {
                "Nome": "Poção dos Números Explosivos",
                "Descrição": "Resolver exercícios de Matemática / Ciências",
                "Atributo": "Sabedoria",
                "Dificuldade": dificuldades_escola["Matemática / Ciências"],
                "Tempo da missão": 40,
                "Teste": "D20 + Sabedoria",
                "Sucesso": "Ganha +15 minutos extras e XP dobrado",
                "Falha": "Ganha só metade do XP e atrai o monstro da Bagunça dos Números Dançantes"
            },
            {
                "Nome": "Crônicas da Lingua Histórica Perdida",
                "Descrição": "Resolver os exercícios de Português/Leitura de Livros",
                "Atributo": "Inteligência",
                "Dificuldade": dificuldades_escola["Português / Literatura"],
                "Tempo da missão": 30,
                "Teste": "D20 + Inteligência",
                "Sucesso": "Pode pular uma questão difícil ou trocar por outra.",
                "Falha": "Ganha só metade do XP e atrai o monstro"
            },
            {
                "Nome": "Runas da Localização Histórica",
                "Descrição": "Resolver os exercícios de História / Geografia",
                "Atributo": "Inteligência",
                "Dificuldade": dificuldades_escola["História / Geografia"],
                "Tempo da missão": 30,
                "Teste": "D20 + Inteligência",
                "Sucesso": "Pode pesquisar no Gemini  para resolver 1 questão",
                "Falha": "Ganha só metade do XP e atrai o monstro da Perda de Memória e Tempo"
            }
        ],
        "casa": [
            {
                "Nome": "Louça dos Espíritos Invisíveis",
                "Descrição": "Lavar prato, talheres e copo após refeição.",
                "Atributo": "Destreza",
                "Dificuldade": dificuldades_casa["Lavar a Louça"],
                "Tempo da missão": "Livre",
                "Teste": "D20 + Destreza",
                "Sucesso": "Evita perder XP se saiu da mesa e esqueceu",
                "Falha": "Ganha só metade do XP e atrai o monstro da Sujeira Malévola"
            },
            {
                "Nome": "Espírito Guardião do Quarto",
                "Descrição": "Guardar roupas, arrumar a cama, recolher cadernos e objetos espalhados, deixar o quarto limpo e em ordem.",
                "Atributo": "Reflexo",
                "Dificuldade": dificuldades_casa["Arrumar Quarto"],
                "Tempo da missão": 30,
                "Teste": "D20 + Reflexo",
                "Sucesso": "Ganha 15 minutos extras de tela",
                "Falha": "Ganha só metade do XP e atrai o Monstro da Bagunça Sombria."
            },
            {
                "Nome": "Ritual do Corpo Luminoso",
                "Descrição": "Tomar banho, escovar dentes e cabelo.",
                "Atributo": "Sabedoria",
                "Dificuldade": dificuldades_casa["Higiene"],
                "Tempo da missão": 30,
                "Teste": "D20 + Sabedoria",
                "Sucesso": "Ganha 10 minutos extra",
                "Falha": "Ganha só metade do XP e atrai o monstro do Fedor Supremo"
            }
        ]
    }

    print("\nTudo pronto aventureiro, as missões foram ajustadas pelo Mago Supremo!")
    return ficha_personagem, missoes

# Supondo que 'ficha_do_heroi' já está definida
if 'ficha_do_heroi' in locals():
    ficha_com_missoes = agente_missoes(ficha_do_heroi)
    #print("\nFicha do Herói com as Missões Ajustadas:", ficha_com_missoes)
else:
    print("Por favor, execute o Agente 1 primeiro para obter a ficha do personagem.")

################################################
# ---      Agente 3: Print Missões         --- #
################################################
import os
import matplotlib.pyplot as plt
from PIL import Image
from google.colab import drive

drive.mount('/content/drive')

def agente_mostrar_missoes(ficha_do_heroi, missoes):
    """
    Agente 3: Recebe a ficha do herói e as missões e exibe as fichas de imagem
    das missões, indicando o nome e a dificuldade.
    """
    print("\nAGENTE 3: Apresentando as fichas das suas missões personalizadas, aventureiro(a)!")

    pasta_fichas_missoes = '/content/drive/MyDrive/FichasMissoes'

    print("\nSuas Missões Personalizadas:")

    for tipo_missao, lista_missoes in missoes.items():
        for missao in lista_missoes:
            nome_arquivo_missao = f"{missao['Nome'].lower().replace(' ', '_')}.png"
            caminho_ficha_missao = os.path.join(pasta_fichas_missoes, nome_arquivo_missao)

            try:
                img = Image.open(caminho_ficha_missao)
                plt.figure(figsize=(8, 6))
                plt.imshow(img)
                plt.axis('off')
                plt.title(f"{missao['Nome']} (Dificuldade: {missao['Dificuldade']})")
                plt.show()
            except FileNotFoundError:
                print(f"Erro: Arquivo da ficha da missão não encontrado em {caminho_ficha_missao}")
            except Exception as e:
                print(f"Ocorreu um erro ao abrir a imagem da ficha da missão: {e}")

    print("\nA visualização das suas missões está completa!")

# Para usar o Agente 3 (depois de executar os Agentes 1 e 2):
# Supondo que 'ficha_do_heroi' e 'ficha_com_missoes' estejam definidos
# (onde 'ficha_com_missoes' é o retorno do agente_missoes)
if 'ficha_do_heroi' in locals() and 'ficha_com_missoes' in locals():
    agente_mostrar_missoes(ficha_do_heroi, ficha_com_missoes[1])
else:
    print("Por favor, execute os Agentes 1 e 2 primeiro.")

################################################
# ---      Agente 4: Agenda Google         --- #
################################################
import os
from IPython.display import display, HTML
from google.colab import drive
import urllib.parse
import matplotlib.pyplot as plt
from PIL import Image

drive.mount('/content/drive')

def agente_agenda_xp():
    """
    Agente 4: Gera um link para adicionar um lembrete no Google Calendar
    e exibe uma imagem PNG com as instruções de como contar XP e Fragmentos de Memória.
    """
    print("\nO Mago Supremo está preparando um auxílio para a contagem dos seus feitos diários!")

    # --- Geração do link para o Google Calendar (usando HTML) ---
    titulo_evento = urllib.parse.quote_plus("Lembrete: Contabilizar XP e Fragmentos de Memória")
    detalhes_evento = urllib.parse.quote_plus("Lembre-se de contabilizar o XP das missões do dia e rolar 1D8 por tarefa para ver quantos Fragmentos de Memória você conquistou.")
    hora_evento = "21" # Hora em formato 24 horas
    minuto_evento = "00"
    data_inicial = "20250517" # Uma data inicial qualquer para o link funcionar
    data_final = "20260517" # Uma data final qualquer para o link de recorrência

    link_recorrencia = f"https://calendar.google.com/calendar/r/eventedit?dates={data_inicial}T{hora_evento}{minuto_evento}00/{data_final}T{hora_evento}{minuto_evento}00&text={titulo_evento}&details={detalhes_evento}&sf=true&recur=RRULE:FREQ=DAILY"

    html_link = f"""

    Aqui está o lembrete mágico para não esquecer de contabilizar seus feitos aventureiro(a), não perca esse lembrete:\n

    <a href="{link_recorrencia}" target="_blank">Adicionar ao Google Calendar</a>
    """
    display(HTML(html_link))

    # --- Exibição das instruções de contagem da imagem PNG ---
    pasta_contagem_xp = '/content/drive/MyDrive/ContagemXP' # Ajuste o caminho se necessário
    nome_arquivo_contagem = 'contagem_fragmentos_de_memoria_e_XP.png'
    caminho_arquivo_contagem = os.path.join(pasta_contagem_xp, nome_arquivo_contagem)

    try:
        img = Image.open(caminho_arquivo_contagem)
        plt.figure(figsize=(8, 6))
        plt.imshow(img)
        plt.axis('off')
        plt.title("Como Contar seus Fragmentos de Memória e XP")
        plt.show()
    except FileNotFoundError:
        print(f"Erro: Arquivo de instruções (imagem) não encontrado em {caminho_arquivo_contagem}")
    except Exception as e:
        print(f"Ocorreu um erro ao abrir o arquivo de instruções (imagem): {e}")

    print("\nProjeto finalizado! O Mago Supremo se despede e deseja uma jornada épica!")

# Para usar o Agente 4:
agente_agenda_xp()